#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\BlogController::index

article_add:
  path: /add
  controller: App\Controller\BlogController::add

article_show:
  path: /show/{id}
  controller: App\Controller\BlogController::show

article_edit:
  path: /edit/{id}
  controller: App\Controller\BlogController::edit
  requirements:
    id: '\d+'

article_remove:
  path: /remove/{id}
  controller: App\Controller\BlogController::remove
  requirements:
    id: '\d+'

article_remove_image:
  path: /remove/image/{id}
  controller: App\Controller\BlogController::removeImage
  requirements:
    id: '\d+'

article_remove_video:
  path: /remove/video/{id}
  controller: App\Controller\BlogController::removeVideo
  requirements:
    id: '\d+'